Repository googleapis/google-auth-library-nodejs, pull requests merged in 2018-07, with the labels that each got.

#400 fix: use `Buffer.from` instead of `new Buffer`
  src/auth/oauth2client.ts
  test/test.oauth2.ts
Labels: cla: yes, in progress

#401 fix: drop support for node.js 4.x
  .circleci/config.yml
  package.json
  tsconfig.json
Labels: cla: yes, in progress, semver: major

#399 fix: Warn when using user credentials from the Cloud SDK
  package-lock.json
  src/auth/googleauth.ts
  src/messages.ts
  test/test.googleauth.ts
Labels: cla: yes, in progress

#402 fix: deprecate the `getDefaultProjectId` method
  package-lock.json
  package.json
  src/auth/googleauth.ts
  src/messages.ts
  test/fixtures/kitchen/src/index.ts
  test/test.googleauth.ts
Labels: cla: yes, in progress

#409 fix: use gcp-metadata for compute credentials
  package.json
  src/auth/computeclient.ts
  src/auth/oauth2client.ts
  test/test.compute.ts
  test/test.googleauth.ts
  test/test.oauth2.ts
Labels: cla: yes, in progress

#404 fix: prevent unhandled rejections by avoid .catch
  package-lock.json
  src/auth/googleauth.ts
  src/auth/jwtaccess.ts
  src/auth/jwtclient.ts
  src/auth/oauth2client.ts
  src/auth/refreshclient.ts
  src/transporters.ts
Labels: cla: yes, in progress

#412 refactor: cleanup types for certificates
  src/auth/oauth2client.ts
  test/test.oauth2.ts
Labels: cla: yes, in progress

#413 fix: surface file read stream errors
  package-lock.json
  package.json
  src/auth/googleauth.ts
  test/test.googleauth.ts
Labels: cla: yes, in progress

#415 refactor: use assert.reject in the tests
  test/test.compute.ts
  test/test.googleauth.ts
  test/test.jwt.ts
  test/test.kitchen.ts
  test/test.oauth2.ts
  test/test.transporters.ts
Labels: cla: yes, in progress

#417 fix: cleanup the circleCI config
  .circleci/config.yml
Labels: cla: yes, in progress

#410 fix: deprecate the `createScopedRequired` methods
  src/auth/computeclient.ts
  src/auth/iam.ts
  src/auth/jwtaccess.ts
  src/auth/jwtclient.ts
  src/messages.ts
  test/test.compute.ts
  test/test.iam.ts
  test/test.jwt.ts
  test/test.jwtaccess.ts
Labels: cla: yes, in progress

#414 chore: deprecate getRequestMetadata
  package-lock.json
  src/auth/googleauth.ts
  src/auth/iam.ts
  src/auth/jwtaccess.ts
  src/auth/jwtclient.ts
  src/auth/oauth2client.ts
  src/auth/refreshclient.ts
  src/messages.ts
  test/test.iam.ts
  test/test.jwt.ts
  test/test.jwtaccess.ts
  test/test.oauth2.ts
Labels: cla: yes, in progress

#423 Fix broken link
  README.md
Labels: cla: yes

#425 test: use strictEqual in tests
  package-lock.json
  test/test.compute.ts
  test/test.googleauth.ts
  test/test.iam.ts
  test/test.jwt.ts
  test/test.jwtaccess.ts
  test/test.loginticket.ts
  test/test.oauth2.ts
  test/test.refresh.ts
  test/test.transporters.ts
Labels: cla: yes, in progress

#434 fix: Use new auth URIs
  src/auth/oauth2client.ts
  test/test.oauth2.ts
Labels: cla: yes, in progress
