Repository googleapis/google-auth-library-nodejs, pull requests merged in 2018-03, with the labels that each got.

#304 Fixe typo in comment
  src/auth/jwtclient.ts
Labels: cla: yes

#306 chore: rename `credential` to `client`
  README.md
  src/auth/googleauth.ts
  test/test.googleauth.ts
Labels: 2.0, cla: yes, semver-major

#305 chore: drop support for node.js 4
  .circleci/config.yml
  package.json
  tsconfig.json
Labels: 2.0, cla: yes, semver-major

#310 chore: cleanup iam interface
  src/auth/googleauth.ts
  src/auth/iam.ts
  test/test.iam.ts
Labels: 2.0, cla: yes, semver-major

#308 chore: improve tests
  test/test.compute.ts
  test/test.googleauth.ts
  test/test.jwtaccess.ts
Labels: cla: yes

#307 fix: limit situations where we retry
  src/auth/oauth2client.ts
  test/test.compute.ts
Labels: 2.0, cla: yes, semver-major

#316 fix: increase test timeout
  package.json
Labels: cla: yes

#317 chore: update deps
  package-lock.json
  package.json
Labels: cla: yes

#319 chore: remove tokenUrl option
  package-lock.json
  package.json
  src/auth/computeclient.ts
  src/auth/oauth2client.ts
  test/test.compute.ts
  test/test.googleauth.ts
  test/test.oauth2.ts
Labels: cla: yes

#318 feat: get rid of createScopedRequired
  README.md
  examples/keepalive.js
  package-lock.json
  src/auth/computeclient.ts
  src/auth/googleauth.ts
  src/auth/iam.ts
  src/auth/jwtaccess.ts
  src/auth/jwtclient.ts
  test/test.compute.ts
  test/test.googleauth.ts
  test/test.jwt.ts
  test/test.jwtaccess.ts
Labels: cla: yes

#324 fix: ensure GCF can read metadata requests
  src/auth/googleauth.ts
  test/test.googleauth.ts
Labels: cla: yes

#325 chore: release 1.3.2
  package.json
Labels: cla: yes

#322 fix: don't duplicate user-agent
  src/transporters.ts
  test/test.transporters.ts
Labels: cla: yes

#323 feat: add JWT.getCredentials method
  package-lock.json
  package.json
  src/auth/credentials.ts
  src/auth/googleauth.ts
  src/auth/jwtclient.ts
  test/fixtures/key.p12
  test/test.jwt.ts
Labels: cla: yes

#329 chore: setup nightly builds workflow
  .circleci/config.yml
  .circleci/get_workflow_name.py
Labels: cla: yes

#328 fix: use id_token for IAP requests
  src/auth/credentials.ts
  src/auth/jwtclient.ts
  test/test.jwt.ts
Labels: cla: yes

#337 feat: add getTokenInfo method
  README.md
  examples/jwt.js
  examples/oauth2.js
  package-lock.json
  src/auth/oauth2client.ts
  test/test.oauth2.ts
Labels: cla: yes, semver-minor
