Repository googleapis/google-auth-library-nodejs, pull requests merged in 2018-12, with the labels that each got.

#547 fix(build): fix system key decryption
  .circleci/config.yml
Labels: cla: yes

#551 chore: update license file
  LICENSE
Labels: cla: yes

#552 chore(build): update the prettier and renovate config
  .prettierignore
  .prettierrc
  renovate.json
Labels: cla: yes

#554 docs: clean up the readme
  CHANGELOG.md
  README.md
Labels: cla: yes

#553 docs: add ref docs again
  .compodocrc
  package.json
Labels: cla: yes

#556 chore: nyc ignore build/test by default
  .nycrc
  package.json
Labels: cla: yes

#557 chore: always nyc report before calling codecov
  .kokoro/test.sh
Labels: cla: yes

#561 build: add Kokoro configs for autorelease
  .circleci/config.yml
  .circleci/npm-install-retry.js
  .kokoro/publish.sh
  .kokoro/release/publish.cfg
Labels: cla: yes

#562 fix(build): fix Kokoro release script
  .kokoro/release/publish.cfg
Labels: cla: yes

#563 chore: fix publish.sh perm
  .kokoro/publish.sh
Labels: cla: yes

#565 chore: update nyc and eslint configs
  .eslintignore
  .nycrc
Labels: cla: yes

#566 chore(build): inject yoshi automation key
  .kokoro/release/publish.cfg
Labels: cla: yes

#559 refactor: use execa for install tests, run eslint on samples
  .gitignore
  AUTHORS
  package.json
  samples/.eslintrc.yml
  samples/adc.js
  samples/authRequest.js
  samples/compute.js
  samples/creds.js
  samples/fromJSON.js
  samples/iap.js
  samples/jwt.js
  samples/keepalive.js
  samples/keyfile.js
  samples/oauth2-codeVerifier.js
  samples/oauth2.js
  samples/package.json
  samples/puppeteer/.eslintrc.yml
  samples/puppeteer/oauth2-test.js
  samples/puppeteer/package.json
  samples/refreshAccessToken.js
  samples/verifyIdToken.js
  system-test/test.kitchen.ts
Labels: cla: yes

#573 Release google-auth-library v2.0.2
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#536 fix(deps): upgrade to gcp-metadata v0.9.0
  package.json
  src/auth/computeclient.ts
  src/auth/googleauth.ts
Labels: cla: yes, semver: major

#578 fix: accept lowercase env vars
  src/auth/googleauth.ts
  test/test.googleauth.ts
Labels: cla: yes
