Repository googleapis/google-auth-library-nodejs, pull requests merged in 2019-05, with the labels that each got.

#685 chore: remove Node.js v6 CI
  .kokoro/continuous/node6/common.cfg
  .kokoro/continuous/node6/test.cfg
  .kokoro/presubmit/node6/common.cfg
  .kokoro/presubmit/node6/test.cfg
Labels: cla: yes

#686 build!: upgrade engines field to >=8.10.0
  package.json
Labels: cla: yes

#687 chore: do not run CI on grpc-js
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
Labels: cla: yes

#692 build: only pipe to codecov if tests run in Node 10
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes

#695 build: patch Windows container, fixing Node 10
  .kokoro/test.bat
Labels: automerge, cla: yes

#693 test: make tests work on Windows and in GCE
  test/test.googleauth.ts
Labels: cla: yes

#699 [CHANGE ME] Re-generated to pick up changes in the API or client library generator.
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/test.cfg
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/test.cfg
  synth.metadata
Labels: cla: yes

#702 fix(deps): update dependency gtoken to v3
  package.json
Labels: cla: yes

#690 chore: remove bonus dependencies
  package.json
  test/mocha.opts
  test/test.compute.ts
  test/test.googleauth.ts
  test/test.oauth2.ts
  test/test.transporters.ts
Labels: cla: yes

#703 chore: release 4.0.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#709 build: updated kokoro config for coverage and release-please
  .kokoro/continuous/node10/test.cfg
  .kokoro/release-candidate-issue.sh
  .kokoro/release-requested.sh
  .kokoro/release/publish.cfg
  .kokoro/release/release-candidate-issue.cfg
  .kokoro/release/release-requested.cfg
  .kokoro/test.sh
  synth.metadata
Labels: automerge, cla: yes

#717 build: add configuration for automated doc deployment
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
Labels: cla: yes

#718 build: ignore proto files in test coverage
  .nycrc
Labels: cla: yes

#719 feat: use X-Goog-Api-Key header
  package.json
  src/auth/oauth2client.ts
  test/test.googleauth.ts
Labels: cla: yes

#720 chore: release 4.1.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#721 fix: shell jobs were outputting too much information
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
Labels: cla: yes

#722 fix: pad base64 strings for base64js
  browser-test/test.crypto.ts
  src/crypto/browser/crypto.ts
  src/crypto/crypto.ts
  test/test.crypto.ts
Labels: cla: yes

#723 build: remove verbose logging from browser test
  .kokoro/browser-test.sh
Labels: cla: yes
