Repository googleapis/google-auth-library-nodejs, pull requests merged in 2020-07, with the labels that each got.

#988 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#990 chore: address linting issues
  src/auth/computeclient.ts
  src/auth/googleauth.ts
  src/auth/iam.ts
  src/auth/idtokenclient.ts
  src/auth/jwtaccess.ts
  src/auth/jwtclient.ts
  src/auth/oauth2client.ts
  src/auth/refreshclient.ts
  src/messages.ts
  src/options.ts
  system-test/fixtures/kitchen/src/index.ts
  test/test.googleauth.ts
  test/test.jwt.ts
  test/test.jwtaccess.ts
  test/test.oauth2.ts
  test/test.refresh.ts
Labels: cla: yes

#993 fix: typeo in nodejs .gitattribute
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#1005 build: missing closing paren in publish script
  .kokoro/publish.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#1004 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/browser-test.cfg
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#1007 fix(types): include scope in credentials type
  src/auth/credentials.ts
Labels: cla: yes

#1012 chore: add config files for cloud-rad for node.js, delete Node 8 templates
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: automerge, cla: yes, context: partial

#1014 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#1015 build: rename _toc to toc
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#1017 build: move gitattributes files to node templates
  .gitattributes
  synth.metadata
Labels: cla: yes, context: full

#1018 chore(node): fix kokoro build path for cloud-rad
  .kokoro/release/docs-devsite.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full
