Repository googleapis/google-auth-library-nodejs, pull requests merged in 2020-11, with the labels that each got.

#1094 build(node): add KOKORO_BUILD_ARTIFACTS_SUBDIR to env
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: cla: yes, context: full

#1095 docs: use the common readme template
  .readme-partials.yaml
  README.md
  samples/README.md
  synth.metadata
  synth.py
Labels: cla: yes

#1096 chore: start tracking obsolete files
  synth.metadata
Labels: cla: yes, context: full

#1101 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: full
