Repository googleapis/google-auth-library-nodejs, pull requests merged in 2020-12, with the labels that each got.

#1102 tests: fixes broken browser tests
  .github/workflows/ci.yaml
  .kokoro/release/docs-devsite.sh
  .kokoro/trampoline_v2.sh
  .readme-partials.yaml
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  README.md
  package.json
  samples/README.md
  samples/package.json
  src/auth/baseexternalclient.ts
  src/auth/identitypoolclient.ts
  synth.metadata
  synth.py
Labels: cla: no

#1108 fix: move accessToken to headers instead of parameter
  src/auth/oauth2client.ts
  test/test.oauth2.ts
Labels: cla: yes

#1110 docs: add instructions for authenticating for system tests
  CONTRIBUTING.md
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: full
