Repository googleapis/google-auth-library-nodejs, pull requests merged in 2020-08, with the labels that each got.

#991 fix: migrate token info API to not pass token in query string
  src/auth/oauth2client.ts
  test/test.oauth2.ts
Labels: cla: yes

#1022 feat: defines internal utils for OAuth client Auth and error handling
  src/auth/oauth2common.ts
  test/test.oauth2common.ts
Labels: cla: yes, do not merge

#1025 refactor(samples): idtoken-cloudrun => idtoken-serverless
  README.md
  samples/README.md
  samples/idtokens-serverless.js
  samples/test/jwt.test.js
Labels: cla: yes

#1027 docs: README updated with new sample paths
  samples/README.md
  synth.metadata
Labels: cla: yes, context: none

#1026 feat: implements the OAuth token exchange spec based on rfc8693
  README.md
  samples/README.md
  samples/idtokens-serverless.js
  samples/test/jwt.test.js
  src/auth/oauth2common.ts
  src/auth/stscredentials.ts
  synth.metadata
  test/test.oauth2common.ts
  test/test.stscredentials.ts
Labels: cla: yes

#1029 build: credential-file-override is no longer required
  .kokoro/populate-secrets.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#1034 chore: update cloud rad kokoro build job
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#1035 build: perform publish using Node 12
  .kokoro/release/publish.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#1030 feat: defines ExternalAccountClient abstract class for external_account credentials
  .kokoro/populate-secrets.sh
  .kokoro/release/docs-devsite.sh
  CHANGELOG.md
  package.json
  src/auth/externalclient.ts
  synth.metadata
  test/test.externalclient.ts
Labels: cla: yes

#1040 docs: correct spelling of its
  src/auth/oauth2client.ts
Labels: automerge: exact, cla: yes

#1041 feat: adds service account impersonation to `ExternalAccountClient`
  .kokoro/release/publish.cfg
  CHANGELOG.md
  package.json
  samples/package.json
  src/auth/externalclient.ts
  synth.metadata
  test/test.externalclient.ts
Labels: cla: no

#1031 docs: ensure to await auth.getIdTokenClient in readme
  README.md
Labels: cla: yes

#1043 chore: start tracking obsolete files
  synth.metadata
Labels: automerge, cla: yes, context: full

#1046 feat: adds crypto utils for AWS request signing
  .kokoro/continuous/node12/lint.cfg
  .kokoro/continuous/node12/samples-test.cfg
  .kokoro/continuous/node12/system-test.cfg
  .kokoro/presubmit/node12/samples-test.cfg
  .kokoro/presubmit/node12/system-test.cfg
  README.md
  browser-test/test.crypto.ts
  src/auth/oauth2client.ts
  src/crypto/browser/crypto.ts
  src/crypto/crypto.ts
  src/crypto/node/crypto.ts
  synth.metadata
  test/test.crypto.ts
Labels: cla: yes

#1048 build: track flaky tests for "nightly", add new secrets for tagging
  .github/publish.yml
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#1047 feat: implements AWS signature version 4 for signing requests
  browser-test/test.crypto.ts
  src/auth/awsrequestsigner.ts
  src/crypto/crypto.ts
  test/fixtures/aws-security-credentials.json
  test/test.awsrequestsigner.ts
  test/test.crypto.ts
Labels: cla: yes

#1049 feat: defines `AwsClient` used for AWS workloads
  .github/publish.yml
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  browser-test/test.crypto.ts
  src/auth/awsclient.ts
  src/auth/baseexternalclient.ts
  synth.metadata
  test/fixtures/aws-security-credentials-fake.json
  test/test.awsclient.ts
  test/test.awsrequestsigner.ts
Labels: cla: yes
