Repository googleapis/google-auth-library-nodejs, pull requests merged in 2020-06, with the labels that each got.

#969 build: migrate to secret manager
  .kokoro/populate-secrets.sh
  .kokoro/publish.sh
  .kokoro/release/publish.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#971 chore(nodejs_templates): add script logging to node_library populate-secrets.sh
  .kokoro/populate-secrets.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#975 docs: update JWT sample
  README.md
Labels: cla: yes

#974 fix(types): add locale property to idtoken
  src/auth/loginticket.ts
Labels: automerge, cla: yes

#972 fix(tsc): audience property is not mandatory on verifyIdToken
  src/auth/oauth2client.ts
Labels: cla: yes

#952 chore: add Blunderbuss config
  .github/blunderbuss.yml
Labels: cla: yes

#978 chore: update node issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  synth.metadata
Labels: automerge, cla: yes, context: full

#982 build: add config .gitattributes
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full
