Repository googleapis/google-auth-library-nodejs, pull requests merged in 2020-05, with the labels that each got.

#954 chore: unpin version of gts
  package.json
Labels: automerge, cla: yes

#956 fix: gcp-metadata now warns rather than throwing
  package.json
  test/test.googleauth.ts
Labels: cla: yes

#957 build: do not fail builds on codecov errors (#528)
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#965 fix: fixing tsc error caused by @types/node update
  test/test.googleauth.ts
  test/test.jwt.ts
  test/test.oauth2.ts
Labels: cla: yes
