Repository googleapis/google-auth-library-nodejs, pull requests merged in 2021-01, with the labels that each got.

#1117 test: add integration tests for external account clients
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  package.json
  samples/package.json
  samples/scripts/externalclient-setup.js
  samples/test/externalclient.test.js
  src/auth/oauth2client.ts
  synth.metadata
  test/test.oauth2.ts
Labels: cla: yes, kokoro:force-run

#1120 fix: support PEM and p12 when using factory
  src/auth/googleauth.ts
  test/test.googleauth.ts
  test/test.jwt.ts
Labels: cla: yes

#1116 fix: call addSharedMetadataHeaders even when token has not expired
  src/auth/oauth2client.ts
  test/test.refresh.ts
Labels: automerge: secure, cla: yes

#1124 refactor(nodejs): move build cop to flakybot
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#1122 test: add integration tests for AWS external account clients
  package.json
  samples/scripts/externalclient-setup.js
  samples/test/externalclient.test.js
  src/auth/googleauth.ts
  test/test.googleauth.ts
  test/test.jwt.ts
Labels: cla: yes
