Repository googleapis/google-auth-library-nodejs, pull requests merged in 2021-04, with the labels that each got.

#1148 build: revert temporary mocha fix
  system-test/test.kitchen.ts
Labels: cla: yes

#1153 fix: do not suppress external project ID determination errors
  src/auth/googleauth.ts
  test/test.googleauth.ts
Labels: automerge, cla: yes

#1159 chore: regenerate common templates
  .github/workflows/ci.yaml
  .kokoro/release/publish.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#1163 docs: add ADC instructions
  README.md
  synth.metadata
Labels: cla: yes, context: none

#1169 build: add generated-files bot config
  .github/generated-files-bot.yml
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
