Repository googleapis/google-auth-library-nodejs, pull requests merged in 2022-04, with the labels that each got.

#1390 chore(deps): Update `gtoken`'s minimum version
  package.json
Labels: size: xs

#1393 refactor!: remove deprecated DeprecatedGetClientOptions
  src/auth/googleauth.ts
  src/auth/oauth2client.ts
  test/test.googleauth.ts
  test/test.oauth2.ts
Labels: priority: p2, semver: major, Breaking Change, size: s

#1392 build!: Set Node v12 to minimum supported version & Upgrade TypeScript
  .github/sync-repo-settings.yaml
  .github/workflows/ci.yaml
  .kokoro/continuous/node10/common.cfg
  .kokoro/continuous/node10/docs.cfg
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/browser-test.cfg
  .kokoro/continuous/node8/common.cfg
  .kokoro/continuous/node8/test.cfg
  .kokoro/presubmit/node10/common.cfg
  .kokoro/presubmit/node10/docs.cfg
  .kokoro/presubmit/node10/lint.cfg
  .kokoro/presubmit/node10/test.cfg
  package.json
  samples/package.json
  samples/puppeteer/package.json
  src/auth/baseexternalclient.ts
  src/auth/computeclient.ts
  src/auth/identitypoolclient.ts
  src/auth/impersonated.ts
  src/auth/oauth2client.ts
  src/auth/stscredentials.ts
  src/transporters.ts
  test/test.awsclient.ts
  test/test.externalclient.ts
  test/test.googleauth.ts
  test/test.jwt.ts
  test/test.jwtaccess.ts
  test/test.refresh.ts
Labels: priority: p2, semver: major, Breaking Change, eol, size: m

#1397 fix: Fixing Implementation of GoogleAuth.sign() for external account credentials
  src/auth/googleauth.ts
  test/test.googleauth.ts
Labels: size: s
