Repository googleapis/google-auth-library-nodejs, pull requests merged in 2022-08, with the labels that each got.

#1431 feat: adding executable and file handling for Pluggable Auth Client
  README.md
  samples/test/externalclient.test.js
  src/auth/executable-response.ts
  src/auth/externalclient.ts
  src/auth/pluggable-auth-client.ts
  src/auth/pluggable-auth-handler.ts
  src/index.ts
  test/test.executableresponse.ts
  test/test.externalclient.ts
  test/test.pluggableauthclient.ts
  test/test.pluggableauthhandler.ts
Labels: size: xl

#1437 feat: adds Pluggable Auth support
  .readme-partials.yaml
  README.md
  samples/test/externalclient.test.js
  src/auth/baseexternalclient.ts
  src/auth/executable-response.ts
  src/auth/externalclient.ts
  src/auth/pluggable-auth-client.ts
  src/auth/pluggable-auth-handler.ts
  src/index.ts
  test/test.executableresponse.ts
  test/test.externalclient.ts
  test/test.pluggableauthclient.ts
  test/test.pluggableauthhandler.ts
Labels: size: xl

#1439 feat: Add `generateIdToken` support for `Impersonated` Clients
  src/auth/impersonated.ts
  test/test.impersonated.ts
Labels: size: m

#1436 refactor: remove comment and promises, instead only using async/await
  src/auth/googleauth.ts
Labels: size: s

#1427 fix(functions): clarify auth comments
  samples/idtokens-serverless.js
Labels: api: cloudfunctions, size: s

#1426 fet(deps): gtoken with support for transporter
  package.json
  src/auth/jwtclient.ts
Labels: size: xs

#1441 feat: adding configurable token lifespan support
  .readme-partials.yaml
  README.md
  samples/test/externalclient.test.js
  src/auth/baseexternalclient.ts
  test/externalclienthelper.ts
  test/test.baseexternalclient.ts
Labels: size: m

#1450 docs: adding workforce documentation to readme
  .readme-partials.yaml
  README.md
Labels: size: l

#1447 fix: remove `projectId` check for `signBlob` calls
  src/auth/googleauth.ts
  test/test.googleauth.ts
Labels: size: m

#1448 feat: Support Not Requiring `projectId` When Not Required
  src/auth/googleauth.ts
  test/test.googleauth.ts
Labels: size: m

#1454 fix: do not use #private
  src/auth/googleauth.ts
Labels: size: s
