Repository googleapis/google-auth-library-nodejs, pull requests merged in 2022-11, with the labels that each got.

#1478 feat: Introduce environment variable for quota project
  src/auth/authclient.ts
  src/auth/googleauth.ts
  test/test.googleauth.ts
Labels: size: m

#1486 refactor: Validate AWS Metadata URLs
  src/auth/awsclient.ts
  test/test.awsclient.ts
Labels: size: m

#1487 chore(issue-1485): clarify audience + url example usage
  samples/idtokens-serverless.js
Labels: size: xs

#1488 refactor: Unify `GoogleAuth#fromJSON` logic + fix sample
  samples/idTokenFromServiceAccount.js
  src/auth/googleauth.ts
  src/auth/refreshclient.ts
Labels: samples, size: m

#1493 fix: do not call metadata server if security creds and region are retrievable through environment vars
  src/auth/awsclient.ts
  src/auth/awsrequestsigner.ts
  test/test.awsclient.ts
Labels: size: l

#1494 refactor(test): Use Native FS Temp Directory Tools
  package.json
  system-test/test.kitchen.ts
Labels: size: s
