Repository googleapis/google-auth-library-nodejs, pull requests merged in 2023-06, with the labels that each got.

#1561 fix: keepAlive sample
  samples/keepalive.js
Labels: samples, size: s

#1555 fix: IdTokenClient expiry_date check
  src/auth/idtokenclient.ts
Labels: size: xs

#1580 refactor: increase upper webpack bundle limit
  system-test/test.kitchen.ts
Labels: size: xs

#1513 feat: Utilize `gcp-metadata`'s GCP Residency Check
  package.json
  src/auth/googleauth.ts
  test/test.googleauth.ts
Labels: size: m
