Repository googleapis/google-auth-library-nodejs, pull requests merged in 2023-11, with the labels that each got.

#1693 test: Remove Long-Skipped Tests
  samples/test/jwt.test.js
  test/test.transporters.ts
Labels: size: s

#1694 feat: Add impersonated signer
  README.md
  samples/README.md
  samples/signBlobImpersonated.js
  src/auth/googleauth.ts
  src/auth/impersonated.ts
  test/test.googleauth.ts
  test/test.impersonated.ts
Labels: size: m

#1696 fix: Verifier Algorithm
  src/crypto/node/crypto.ts
Labels: size: xs

#1701 test: fix flaky tests when ran on GCP
  test/test.googleauth.ts
Labels: size: xs

#1703 feat: Update gcp metadata dependency
  package.json
Labels: size: xs
