Repository googleapis/google-auth-library-nodejs, pull requests merged in 2023-07, with the labels that each got.

#1583 build!: remove arrify and fast-text-encoding
  browser-test/test.crypto.ts
  browser-test/test.oauth2.ts
  package.json
  src/auth/computeclient.ts
  src/crypto/browser/crypto.ts
  test/test.crypto.ts
Labels: size: s

#1582 chore!: migrate to Node 14
  .github/sync-repo-settings.yaml
  .github/workflows/ci.yaml
  .kokoro/continuous/node12/common.cfg
  .kokoro/continuous/node12/lint.cfg
  .kokoro/continuous/node12/samples-test.cfg
  .kokoro/continuous/node12/system-test.cfg
  .kokoro/continuous/node12/test.cfg
  .kokoro/presubmit/node12/common.cfg
  .kokoro/presubmit/node12/samples-test.cfg
  .kokoro/presubmit/node12/system-test.cfg
  .kokoro/presubmit/node12/test.cfg
  package.json
  samples/package.json
Labels: size: m

#1407 chore!: clean up the Transporter interface.
  src/transporters.ts
  test/test.transporters.ts
Labels: next major: breaking change, size: m

#1406 feat!: make transporter attribute type more generic
  src/auth/authclient.ts
  src/auth/externalAccountAuthorizedUserClient.ts
  src/auth/stscredentials.ts
Labels: next major: breaking change, size: s

#1589 build: Fixing tests that use reqheaders improperly
  test/externalclienthelper.ts
  test/test.awsclient.ts
  test/test.baseexternalclient.ts
  test/test.downscopedclient.ts
  test/test.externalaccountauthorizeduserclient.ts
  test/test.googleauth.ts
  test/test.identitypoolclient.ts
  test/test.oauth2.ts
Labels: size: xl

#1590 chore(deps)!: upgrade node-gtoken to 7.0.0
  package.json
  test/test.googleauth.ts
  test/test.jwt.ts
Labels: size: m

#1592 build: update gaxios & gcp-metadata to 6.0.0, update @types/node to 20.4.2, decrease puppeteer to ^19.0.0, distinguish status and code in error handling.
  package.json
  src/auth/computeclient.ts
  src/transporters.ts
  test/test.awsclient.ts
  test/test.baseexternalclient.ts
  test/test.downscopedclient.ts
  test/test.externalaccountauthorizeduserclient.ts
  test/test.identitypoolclient.ts
  test/test.oauth2.ts
  test/test.transporters.ts
Labels: size: m

#1595 feature: Byoid metrics
  src/auth/awsclient.ts
  src/auth/baseexternalclient.ts
  src/auth/identitypoolclient.ts
  src/auth/pluggable-auth-client.ts
  test/externalclienthelper.ts
  test/test.awsclient.ts
  test/test.baseexternalclient.ts
  test/test.identitypoolclient.ts
  test/test.pluggableauthclient.ts
Labels: kokoro:run, size: l
