Repository googleapis/google-auth-library-nodejs, pull requests merged in 2024-04, with the labels that each got.

#1783 feat: adds support for creating AWS and Identity Pool credentials with custom suppliers.
  src/auth/awsclient.ts
  src/auth/baseexternalclient.ts
  src/auth/externalAccountAuthorizedUserClient.ts
  src/auth/identitypoolclient.ts
  test/test.awsclient.ts
  test/test.baseexternalclient.ts
  test/test.externalaccountauthorizeduserclient.ts
  test/test.identitypoolclient.ts
Labels: size: l

#1790 docs: adding documentation for programmatic auth feature
  .readme-partials.yaml
  src/auth/awsclient.ts
  src/auth/baseexternalclient.ts
  src/auth/identitypoolclient.ts
Labels: size: l

#1791 feat: Enable Retries For Auth Requests
  src/auth/authclient.ts
  src/auth/awsclient.ts
  src/auth/baseexternalclient.ts
  src/auth/downscopedclient.ts
  src/auth/externalAccountAuthorizedUserClient.ts
  src/auth/googleauth.ts
  src/auth/identitypoolclient.ts
  src/auth/impersonated.ts
  src/auth/oauth2client.ts
  src/auth/oauth2common.ts
  src/auth/stscredentials.ts
  test/test.awsclient.ts
  test/test.downscopedclient.ts
  test/test.externalaccountauthorizeduserclient.ts
  test/test.jwt.ts
  test/test.jwtaccess.ts
  test/test.oauth2.ts
  test/test.stscredentials.ts
Labels: size: m

#1794 feat: Improve `gaxios` exposure
  src/auth/authclient.ts
  src/index.ts
Labels: size: s

#1795 feat: adds suppliers for custom subject token and AWS credentials
  .readme-partials.yaml
  README.md
  src/auth/awsclient.ts
  src/auth/baseexternalclient.ts
  src/auth/defaultawssecuritycredentialssupplier.ts
  src/auth/externalAccountAuthorizedUserClient.ts
  src/auth/filesubjecttokensupplier.ts
  src/auth/identitypoolclient.ts
  src/auth/urlsubjecttokensupplier.ts
  test/test.awsclient.ts
  test/test.baseexternalclient.ts
  test/test.externalaccountauthorizeduserclient.ts
  test/test.identitypoolclient.ts
Labels: size: xl

#1805 build: pin `@compodoc/compodoc`
  package.json
Labels: size: xs
