Repository googleapis/google-auth-library-nodejs, pull requests merged in 2024-01, with the labels that each got.

#1718 chore: Skip IAP Sample Test
  samples/test/jwt.test.js
Labels: size: xs

#1709 Docs: update links into authentication content on cloud.google.com
  src/auth/computeclient.ts
  src/auth/idtokenclient.ts
Labels: size: xs

#1719 fix(GoogleAuth): Expand `credentials` type
  src/auth/googleauth.ts
Labels: size: xs

#1728 fix: typos in samples
  samples/jwt.js
  samples/keyfile.js
  samples/scripts/externalclient-setup.js
  samples/test/externalclient.test.js
Labels: samples, size: s

#1732 feat: Improve Universe Domain Ergonomics
  src/auth/googleauth.ts
  src/index.ts
  test/test.googleauth.ts
Labels: size: s

#1722 feat: Use self-signed JWTs when non-default Universe Domains
  src/auth/jwtclient.ts
  test/test.jwt.ts
Labels: size: m

#1721 feat: Open More Endpoints for Customization
  src/auth/baseexternalclient.ts
  src/auth/downscopedclient.ts
  src/auth/googleauth.ts
  src/auth/oauth2client.ts
  src/auth/stscredentials.ts
  test/externalclienthelper.ts
  test/test.baseexternalclient.ts
  test/test.downscopedclient.ts
  test/test.externalclient.ts
  test/test.googleauth.ts
  test/test.identitypoolclient.ts
Labels: size: l

#1740 fix: Revert Missing `WORKFORCE_AUDIENCE_PATTERN`
  src/auth/baseexternalclient.ts
  test/test.baseexternalclient.ts
  test/test.externalclient.ts
  test/test.identitypoolclient.ts
Labels: size: m

#1744 refactor: Consistency Between Langs
  src/auth/downscopedclient.ts
  src/auth/oauth2client.ts
  test/test.downscopedclient.ts
Labels: size: m

#1741 test: Fix TPC Tests When Running on GCP
  test/test.googleauth.ts
Labels: size: s
