Repository googleapis/google-auth-library-nodejs, pull requests merged in 2024-03, with the labels that each got.

#1765 fix: making aws request signer get a new session token each time
  src/auth/awsclient.ts
  test/test.awsclient.ts
Labels: size: s

#1771 feat: `PassThrough` AuthClient
  src/auth/authclient.ts
  src/auth/passthrough.ts
  src/index.ts
  test/test.authclient.ts
  test/test.passthroughclient.ts
Labels: size: m

#1778 refactor(deps): `opn` -> `open`
  samples/oauth2-codeVerifier.js
  samples/oauth2.js
  samples/package.json
  samples/verifyIdToken.js
  src/auth/computeclient.ts
  src/transporters.ts
  test/test.downscopedclient.ts
  test/test.jwt.ts
  test/test.oauth2common.ts
  test/test.pluggableauthclient.ts
  test/test.transporters.ts
Labels: size: m

#1776 feat: refactor AWS and identity pool clients to use suppliers
  src/auth/awsclient.ts
  src/auth/baseexternalclient.ts
  src/auth/defaultawssecuritycredentialssupplier.ts
  src/auth/filesubjecttokensupplier.ts
  src/auth/identitypoolclient.ts
  src/auth/urlsubjecttokensupplier.ts
Labels: size: l
