Repository googleapis/google-auth-library-nodejs, pull requests merged in 2025-02, with the labels that each got.

#1774 refactor!: Move Base AuthClient Types to authclient.ts
  src/auth/authclient.ts
  src/auth/awsclient.ts
  src/auth/awsrequestsigner.ts
  src/auth/baseexternalclient.ts
  src/auth/defaultawssecuritycredentialssupplier.ts
  src/auth/downscopedclient.ts
  src/auth/externalAccountAuthorizedUserClient.ts
  src/auth/googleauth.ts
  src/auth/idtokenclient.ts
  src/auth/jwtaccess.ts
  src/auth/oauth2client.ts
  src/auth/passthrough.ts
  src/auth/stscredentials.ts
  test/externalclienthelper.ts
  test/test.downscopedclient.ts
  test/test.oauth2common.ts
Labels: next major: breaking change, size: m

#1688 refactor!: Remove `Transporter` and `DefaultTransporter` from `GoogleAuth` class
  src/auth/googleauth.ts
Labels: next major: breaking change, size: xs

#1690 refactor!: remove DEFAULT_UNIVERSE from BaseExternalClient
  src/auth/baseexternalclient.ts
  test/test.baseexternalclient.ts
  test/test.externalaccountauthorizeduserclient.ts
Labels: next major: breaking change, size: s

#1861 docs: Update README to Point to Newer Instructions
  .readme-partials.yaml
  README.md
Labels: size: s

#1930 test: Skip webpack v4 test
  system-test/test.kitchen.ts
Labels: size: xs

#1928 feat!: Support Node 18, 20, and 22
  .github/sync-repo-settings.yaml
  .github/workflows/ci.yaml
  package.json
  samples/package.json
Labels: size: s

#1919 refactor!: Remove `messages.ts`
  src/messages.ts
Labels: size: s

#1920 refactor!: Remove `options.ts`
  src/options.ts
  src/transporters.ts
  test/test.transporters.ts
Labels: size: s

#1689 refactor!: remove additionalOptions from AuthClients
  .readme-partials.yaml
  samples/downscopedclient.js
  samples/oauth2-codeVerifier.js
  samples/oauth2.js
  samples/puppeteer/oauth2-test.js
  samples/verifyIdToken.js
  src/auth/awsclient.ts
  src/auth/baseexternalclient.ts
  src/auth/downscopedclient.ts
  src/auth/externalAccountAuthorizedUserClient.ts
  src/auth/externalclient.ts
  src/auth/googleauth.ts
  src/auth/identitypoolclient.ts
  src/auth/jwtclient.ts
  src/auth/oauth2client.ts
  src/auth/pluggable-auth-client.ts
  src/auth/refreshclient.ts
  test/test.baseexternalclient.ts
  test/test.downscopedclient.ts
  test/test.externalaccountauthorizeduserclient.ts
  test/test.externalclient.ts
  test/test.googleauth.ts
  test/test.impersonated.ts
  test/test.jwt.ts
Labels: next major: breaking change, size: l

#1935 refactor: `downscopedClient` fix
  src/auth/downscopedclient.ts
Labels: size: xs

#1936 fix: Circular Dependencies Issue
  README.md
  src/auth/pluggable-auth-client.ts
  src/auth/pluggable-auth-handler.ts
  src/crypto/browser/crypto.ts
  src/crypto/crypto.ts
  src/crypto/node/crypto.ts
  src/crypto/shared.ts
Labels: size: m

#1937 refactor!: Remove `Transporter`
  samples/test/externalclient.test.js
  src/auth/authclient.ts
  src/auth/baseexternalclient.ts
  src/auth/defaultawssecuritycredentialssupplier.ts
  src/auth/downscopedclient.ts
  src/auth/externalAccountAuthorizedUserClient.ts
  src/auth/oauth2client.ts
  src/auth/oauth2common.ts
  src/auth/stscredentials.ts
  src/index.ts
  src/shared.cts
  src/transporters.ts
  test/test.authclient.ts
  test/test.baseexternalclient.ts
  test/test.downscopedclient.ts
  test/test.externalaccountauthorizeduserclient.ts
  test/test.googleauth.ts
  test/test.index.ts
  test/test.oauth2.ts
  test/test.transporters.ts
Labels: size: l

#1938 feat!: `Request` Revamp
  .readme-partials.yaml
  README.md
  browser-test/test.oauth2.ts
  package.json
  samples/idTokenFromMetadataServer.js
  samples/test/externalclient.test.js
  src/auth/authclient.ts
  src/auth/awsclient.ts
  src/auth/awsrequestsigner.ts
  src/auth/baseexternalclient.ts
  src/auth/defaultawssecuritycredentialssupplier.ts
  src/auth/downscopedclient.ts
  src/auth/externalAccountAuthorizedUserClient.ts
  src/auth/googleauth.ts
  src/auth/idtokenclient.ts
  src/auth/jwtaccess.ts
  src/auth/jwtclient.ts
  src/auth/oauth2client.ts
  src/auth/oauth2common.ts
  src/auth/passthrough.ts
  src/auth/refreshclient.ts
  src/auth/stscredentials.ts
  src/auth/urlsubjecttokensupplier.ts
  test/externalclienthelper.ts
  test/test.authclient.ts
  test/test.awsclient.ts
  test/test.awsrequestsigner.ts
  test/test.baseexternalclient.ts
  test/test.downscopedclient.ts
  test/test.externalaccountauthorizeduserclient.ts
  test/test.googleauth.ts
  test/test.identitypoolclient.ts
  test/test.idtokenclient.ts
  test/test.impersonated.ts
  test/test.index.ts
  test/test.jwt.ts
  test/test.jwtaccess.ts
  test/test.oauth2.ts
  test/test.oauth2common.ts
  test/test.passthroughclient.ts
  test/test.refresh.ts
  test/test.stscredentials.ts
Labels: size: l
