Repository googleapis/google-auth-library-nodejs, pull requests merged in 2025-01, with the labels that each got.

#1902 docs(readme): add example for service_account_impersonation_url in clientOptions
  .readme-partials.yaml
  README.md
Labels: size: xs

#1907 docs: sample fix
  samples/authenticateAPIKey.js
Labels: samples, size: xs

#1901 Fix Typo in Documentation
  .readme-partials.yaml
Labels: size: xs

#1909 docs: Provide Guidance for Untrusted JSON creds
  .readme-partials.yaml
  README.md
  src/auth/googleauth.ts
Labels: size: xs

#1921 chore: improve system-test log format
  system-test/test.kitchen.ts
Labels: size: s

#1922 chore: pin `engine.io` to prevent `cookie` breaking change
  package.json
Labels: size: xs

#1923 docs: JSON credential best practices
  src/auth/googleauth.ts
  src/auth/jwtclient.ts
Labels: size: s

#1924 test: Increase timeout for `webpack`
  system-test/test.kitchen.ts
Labels: size: s
