Repository googleapis/google-auth-library-nodejs, pull requests merged in 2025-05, with the labels that each got.

#1965 docs: fix `jsdoc` and `linkinator`
  .github/workflows/ci.yaml
  .jsdoc.js
  linkinator.config.json
  owlbot.py
  package.json
  src/auth/authclient.ts
Labels: size: m

#1967 feat: Implement TrustBoundaries
  src/auth/authclient.ts
  src/auth/baseexternalclient.ts
  src/auth/computeclient.ts
  src/auth/downscopedclient.ts
  src/auth/externalAccountAuthorizedUserClient.ts
  src/auth/impersonated.ts
  src/auth/jwtclient.ts
  src/auth/oauth2client.ts
  src/auth/trustboundary.ts
  test/test.baseexternalclient.ts
  test/test.compute.ts
  test/test.impersonated.ts
  test/test.jwt.ts
Labels: size: l

#2017 Revert "feat: Implement TrustBoundaries"
  src/auth/authclient.ts
  src/auth/baseexternalclient.ts
  src/auth/computeclient.ts
  src/auth/downscopedclient.ts
  src/auth/externalAccountAuthorizedUserClient.ts
  src/auth/impersonated.ts
  src/auth/jwtclient.ts
  src/auth/oauth2client.ts
  src/auth/trustboundary.ts
  test/test.baseexternalclient.ts
  test/test.compute.ts
  test/test.impersonated.ts
  test/test.jwt.ts
Labels: size: l

#2018 Revert "chore(deps): update dependency sinon to v20"
  .github/scripts/package.json
  package.json
Labels: size: xs
